import { join } from "node:path";
import { existsSync, readFileSync, writeFileSync, mkdirSync, appendFileSync } from "node:fs";
import { STASIS_DIR } from "../config.ts";
import type { ShadowState, ShadowEvent, ShadowAdvice, ProjectSprintHistory } from "../types.ts";

const SHADOW_STATE_PATH = join(STASIS_DIR, "shadow-state.json");
const SHADOW_ADVICE_PATH = join(STASIS_DIR, "shadow-advice.json");
const SHADOW_LOG_PATH = join(STASIS_DIR, "shadow-log.md");

const SHADOW_VERSION = 1;
const PRUNE_DAYS = 90;

export function defaultShadowState(): ShadowState {
  return {
    version: SHADOW_VERSION,
    lastCheckMs: 0,
    lastSessionMs: 0,
    projectHistory: {},
    lastCheckProjectOutput: {},
    lastMeta: {},
    pendingEvents: [],
    dailyLog: {},
  };
}

export function loadShadowState(): ShadowState {
  try {
    if (existsSync(SHADOW_STATE_PATH)) {
      const raw = JSON.parse(readFileSync(SHADOW_STATE_PATH, "utf8")) as ShadowState;
      if (raw.version === SHADOW_VERSION) return raw;
    }
  } catch {
    /* fall through */
  }
  return defaultShadowState();
}

export function saveShadowState(s: ShadowState): void {
  mkdirSync(STASIS_DIR, { recursive: true });
  pruneProjectHistory(s);
  writeFileSync(SHADOW_STATE_PATH, JSON.stringify(s, null, 2) + "\n");
}

/** Remove project-history entries inactive for >PRUNE_DAYS. */
function pruneProjectHistory(s: ShadowState): void {
  const cutoff = Date.now() - PRUNE_DAYS * 86_400_000;
  for (const [name, hist] of Object.entries(s.projectHistory)) {
    const lastActive = hist.lastActiveAt ? Date.parse(hist.lastActiveAt) : 0;
    const lastInRoute = hist.lastInRouteAt ? Date.parse(hist.lastInRouteAt) : 0;
    if (lastActive < cutoff && lastInRoute < cutoff) {
      delete s.projectHistory[name];
    }
  }
}

export function writeShadowAdvice(a: ShadowAdvice): void {
  mkdirSync(STASIS_DIR, { recursive: true });
  writeFileSync(SHADOW_ADVICE_PATH, JSON.stringify(a, null, 2) + "\n");
}

export function loadShadowAdvice(): ShadowAdvice | null {
  try {
    if (existsSync(SHADOW_ADVICE_PATH)) {
      return JSON.parse(readFileSync(SHADOW_ADVICE_PATH, "utf8")) as ShadowAdvice;
    }
  } catch {
    /* fall through */
  }
  return null;
}

export function appendShadowLog(dayKey: string, line: string): void {
  const timestamp = new Date().toISOString().slice(11, 19);
  const entry = `[${timestamp}] ${line}\n`;
  mkdirSync(STASIS_DIR, { recursive: true });
  appendFileSync(SHADOW_LOG_PATH, entry, "utf8");
}

export function ensureProjectHistory(s: ShadowState, project: string): ProjectSprintHistory {
  if (!s.projectHistory[project]) {
    s.projectHistory[project] = {
      totalSprintsInRoute: 0,
      totalSprintsDeferred: 0,
      totalEstTokens: 0,
      totalActualTokens: 0,
      lastInRouteAt: null,
      lastActiveAt: null,
    };
  }
  return s.projectHistory[project]!;
}

let _eventCounter = 0;

export function pushEvent(s: ShadowState, kind: ShadowEvent["kind"], project: string | null, message: string, detail: Record<string, unknown> = {}): ShadowEvent {
  _eventCounter++;
  const ev: ShadowEvent = {
    id: `ev-${_eventCounter}-${Date.now()}`,
    ts: Date.now(),
    kind,
    project,
    message,
    detail,
  };
  s.pendingEvents.push(ev);
  return ev;
}

/** Clear events older than the last session mark — they've been consumed by the skill. */
export function pruneEventsSeen(s: ShadowState): void {
  if (!s.lastSessionMs) return;
  s.pendingEvents = s.pendingEvents.filter((e) => e.ts > s.lastSessionMs);
}

export function buildAdvice(s: ShadowState): ShadowAdvice | null {
  const unseen = s.lastSessionMs
    ? s.pendingEvents.filter((e) => e.ts > s.lastSessionMs)
    : s.pendingEvents;

  if (unseen.length === 0) {
    return { hasAdvice: false, summary: "", events: [], generatedAt: new Date().toISOString() };
  }

  const summaries = unseen.map((e) => `  • ${e.message}`);
  return {
    hasAdvice: true,
    summary: `${unseen.length} event${unseen.length > 1 ? "s" : ""} since last session:\n${summaries.join("\n")}`,
    events: unseen,
    generatedAt: new Date().toISOString(),
  };
}

export const SHADOW_LOG_HEADER = `# stasis — shadow log

Auto-generated by \`stasis watch\`. Summarises daily project activity, 
detected events, and advice from the background monitor.

`;
